// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4kb-6nNwzn5lxo1lcP8VYdRkuulHgqq8',
    appId: '1:482984678027:web:ac7595d2abb1c05bf3ba8e',
    messagingSenderId: '482984678027',
    projectId: 'login-otp-9cd84',
    authDomain: 'login-otp-9cd84.firebaseapp.com',
    storageBucket: 'login-otp-9cd84.appspot.com',
    measurementId: 'G-LEXMCJQQMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOs8soMBWTeENQonoS20trYYOhztOvDc',
    appId: '1:482984678027:android:fc08f68aae4e434af3ba8e',
    messagingSenderId: '482984678027',
    projectId: 'login-otp-9cd84',
    storageBucket: 'login-otp-9cd84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3w8FJl2o2UOJ4l14SpXTjTETgmuoApqk',
    appId: '1:482984678027:ios:2736432552a4ca83f3ba8e',
    messagingSenderId: '482984678027',
    projectId: 'login-otp-9cd84',
    storageBucket: 'login-otp-9cd84.appspot.com',
    androidClientId: '482984678027-1n3scaduudjrrahlps3mpl0g0bm453a3.apps.googleusercontent.com',
    iosClientId: '482984678027-4ie11hieci3gdiu4niv9herju2dg99ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3w8FJl2o2UOJ4l14SpXTjTETgmuoApqk',
    appId: '1:482984678027:ios:2736432552a4ca83f3ba8e',
    messagingSenderId: '482984678027',
    projectId: 'login-otp-9cd84',
    storageBucket: 'login-otp-9cd84.appspot.com',
    androidClientId: '482984678027-1n3scaduudjrrahlps3mpl0g0bm453a3.apps.googleusercontent.com',
    iosClientId: '482984678027-4ie11hieci3gdiu4niv9herju2dg99ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginOtp',
  );
}
